### ISSUE TITLE
Edited the victory sprite, now Mighty's jaw's all goofy

### ISSUE THREAD

**Issue by zacnmac** [Techokami/SonicWorldsNext#135] opened 2024-01-25 04:17 UTC
So after replacing Sonic with Mighty, I open the character select screen to find him missing the bottom half of his face.
This is what it's supposed to look like:
![image](https://github.com/Techokami/SonicWorldsNext/assets/143913996/b3498bc9-a362-403b-9514-379a8eac9334)
Instead, however, it looks a little more like so:
![image](https://github.com/Techokami/SonicWorldsNext/assets/143913996/28d642c6-bf14-4f3d-b13d-065af628e934)

**Comment by AsterGTheFourth** [comment] 2024-01-27 03:59
I haven't gone into developing characters in Worlds Next, but perhaps it's the way the sprites are placed?

**Comment by DimensionWarped** [comment] 2024-02-01 18:00
>So after replacing Sonic with mighty

And do you want to elucidate on *how* you did this? Because the easiest way to figure this out isn't to post a blurry picture of how things are supposed to look, it's by posting your sprite sheet and any changes you might have made to Sonic's sprite object.

**Comment by DimensionWarped** [comment] 2024-04-07 21:08
Closing because the person who opened the issue isn't responding and it isn't an issue with the engine itself, but with someone's attempt to modify it.

**Closed by DimensionWarped** 2024-04-07 21:08 UTC
