### ISSUE TITLE
Wall push-out glitch due to slight collision overlap achieved from a normal jump condition

### ISSUE THREAD

**Issue by IeatBabieslmao** [Techokami/SonicWorldsNext#116] opened 2023-12-03 02:06 UTC
https://github.com/Techokami/SonicWorldsNext/assets/142087281/c8f61115-3058-4041-af02-ec574c69538c

**Comment by Techokami** [comment] 2023-12-03 02:17
Why is this a video? Please describe the issue with text instead, where the video is an optional demo of said issue. 

From what I can gather from the footage, the bug appears to be an edge case where jumping off the swinging platform can get the player partially embedded within the wall without being ejected. But that's just my observation, **because you did not actually describe the issue, leaving me to just guess.**

**Comment by IeatBabieslmao** [comment] 2023-12-03 03:04
Sorry, essentially, If you're right at the edge, you slightly clip into the ground, and if you fall onto a spring while in this clipped state, it zips you upwards

**Comment by DimensionWarped** [comment] 2023-12-03 07:29
So I haven't been able to reproduce this myself with the engine running at the default position of everything... it looks like you may have moved the swinging platform a bit. Can you give me the exact coordinates that you put it at?

**Comment by DimensionWarped** [comment] 2023-12-03 08:00
Exact reproduction steps:
1. Use Tails flight to position yourself so that you are just barely going to have your right side collision be considered on ground. Make sure you come to a complete stop before moving to step 2.
2. Start descending. As Tails is about to hit the ground, jump off by holding down + jump (assuming you used single player flight controls, just jump if you used multiplayer flight controls I think? Didn't actually test multiplayer flight mode and it's not important for this issue... either way, just jump off before you hit the ground while riding Tails
3. Wait until Sonic hits the spring and he'll clip.


https://github.com/Techokami/SonicWorldsNext/assets/7477617/8952a757-30ff-4dc4-94ce-0b13cd044988

**Comment by DimensionWarped** [comment] 2023-12-03 08:06
Here is another example without using Tails flight and with the spring removed from the bottom of the chasm.

https://github.com/Techokami/SonicWorldsNext/assets/7477617/833c4a96-156e-45b7-8e36-ec9e93a8688c

**Comment by DimensionWarped** [comment] 2023-12-03 08:08
Renamed the issue due to it not really being about the spring

**Comment by NeonSRB2** [comment] 2024-06-09 03:52
This is due to the horizontal sensor only facing in one direction, if the last direction you moved in was toward the edge the player is ejected like the original games, but if you face away, this happens because the player is never ejected far enough away to not collide upon touching the ground

**Comment by NeonSRB2** [comment] 2024-06-09 04:18
Fixed

**Comment by NeonSRB2** [comment] 2024-06-09 19:02
#159
Hopefully this adds it to the issue list for the pull request?

**Comment by DimensionWarped** [comment] 2024-06-18 04:45
Hey Neon, I'm going to make a point of reviewing those patches over this weekend. Thanks for putting the work in and sorry we've been slow to address your PR.

**Comment by Caverns4** [comment] 2024-09-20 21:39
Since the PR has been long since merged by now, I'd say it's fit to close this issue.

**Closed by Caverns4** 2024-09-20 21:39 UTC
Labels: bug
