### ISSUE TITLE
Layout is weird

### ISSUE THREAD

**Issue by SrDarkOfc** [Techokami/SonicWorldsNext#134] opened 2024-01-22 21:10 UTC
Well, i'm making this bcs **_the layout is way too short._** I'm using godot 4 for Android, the Play Store version. And in it, the layout is way too tiny. I've already made some minor changes at least to make that tiny layout some more comfortable, but it is not really good to make something on such tiny viewport. It is like playing at a TV viewport on a cellphone. So, it needs to be fixed to a 1920 x 1080 version, or it needs to have an option that can change from TV viewport, to cellphone viewport and so on. **Hope this gets fixed soon, because i really liked the engine.**

Explanative screenshots:
![Screenshot_2024-01-22-17-06-51-236_org godotengine editor v4](https://github.com/Techokami/SonicWorldsNext/assets/151418455/5167f166-33ad-4cb8-91bb-b746ad3629e8)
![Screenshot_2024-01-22-17-07-00-460_org godotengine editor v4](https://github.com/Techokami/SonicWorldsNext/assets/151418455/84d404d9-d572-499f-8044-fe9890c0955c)

**Comment by SrDarkOfc** [comment] 2024-01-22 21:15
Half of the screen is completely black because of the little viewport, and also has the problem about the "too big" texts. **I'm using Godot 4 (Android - Play Store version)**

**Comment by Techokami** [comment] 2024-01-22 23:50
Well, we (the development team) are using the regular desktop computer version of Godot for all development. I'm still absolutely baffled that there is even an Android version of *the complete IDE* and that people are trying to make games using it on their phones???

In other words, you're deep in unsupported territory. Probably should put a disclaimer in the readme.

**Comment by Raptorq1** [comment] 2024-01-23 05:46
Okay techokami but some people are saying that they are experiencing the big text on pc as well

**Comment by DimensionWarped** [comment] 2024-01-23 09:57
And they've provided no pictures and haven't even confirmed that the specific issue they are having matches the pictures that have been posted. They also haven't provided platform details of any kind (Whether it's Windows or Linux, specific version/distro of the OS, what kind of video device they are using, etc). There's nothing to go on there until they do.

I'm going to go ahead and say now that we offer no official support for Android... and we *especially* don't support whatever version you get off of the playstore (which 80% of the time means the user doesn't actually *know* what specific version they are using) If it works, great, but for any oddities that come out of it developers are largely on their own. If we had someone join up with experience working with Godot on Android who wanted to tackle these issues, that would be welcome.

@SrDarkOfc Regarding your primary issue, the engine is currently oriented around 4:3 resolutions. I personally feel like it should be oriented around 16:9 and crunched to 4:3 / 16:10 as needed, but I'm not in charge of making that call.

I will tell you that it isn't *that* hard to fix on your local version. You just need to change the viewport resolution. Here's a guide on how to do that:

https://medium.com/codex/set-the-size-of-your-game-window-in-20-sec-godot-4-80241b02333d

Unfortunately, I have no idea what is causing the text issue. I might look into it eventually (using an Android emulator most likely) but right now I have no time for anything.

**Comment by SrDarkOfc** [comment] 2024-01-29 15:57
Uhm, guys if you do don't have any official support for Android, can i actually try and make some changes to the viewport, and call it an Android Version of the engine?
**Ofc you guys will have all the credits from it, i just want to make the viewport suitable for Android Devices**, so people can actually make games for Android, using Android :D

**Comment by DimensionWarped** [comment] 2024-01-29 17:05
> Uhm, guys if you do don't have any official support for Android, can i actually try and make some changes to the viewport, and call it an Android Version of the engine? **Ofc you guys will have all the credits from it, i just want to make the viewport suitable for Android Devices**, so people can actually make games for Android, using Android :D

Feel free to fork as you please. Just because we don't officially support Android also doesn't mean we won't take pull requests to improve usage on Android as long as they don't meaningfully impact the experience for PC users (IE make any changes that present things like on-screen controllers and the like deployment specific)

**Comment by SrDarkOfc** [comment] 2024-01-29 17:42
Hey, one question though. I already made some changes to the viewport, and in the presentations. Unfortunately i couldn't change the title bcs "the scene is invalid/corrupted."

But nevermind, i just wanna know now how do i even start to tweak the camera script for the player :v

![Screenshot_2024-01-29-13-37-08-073_org godotengine editor v4](https://github.com/Techokami/SonicWorldsNext/assets/151418455/79578243-8dd4-4337-baff-b19aeb02b8e3)

Well... I've saw the camera variables on the player script, and i've tried to change some numbers there to make it do something like a "zoom", but it didn't work properly... So if you guys can tell me how i can even start "fixing" that camera, i would finish those tweaks today or tomorrow

**Comment by 2Schoolhouse** [comment] 2024-01-30 02:00
> Hey, one question though. I already made some changes to the viewport, and in the presentations. Unfortunately i couldn't change the title bcs "the scene is invalid/corrupted."
> 
> But nevermind, i just wanna know now how do i even start to tweak the camera script for the player :v
> 
> ![Screenshot_2024-01-29-13-37-08-073_org godotengine editor v4](https://private-user-images.githubusercontent.com/151418455/300554424-79578243-8dd4-4337-baff-b19aeb02b8e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODAyMjIsIm5iZiI6MTcwNjU3OTkyMiwicGF0aCI6Ii8xNTE0MTg0NTUvMzAwNTU0NDI0LTc5NTc4MjQzLThkZDQtNDMzNy1iYWZmLWIxOWFlYjAyYjhlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMTU4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmJiOGVhNTUxYTg3NDIxYTliMzg1NjJjYzU2YTk0ZWNjYzQ2NjZlNjI3YWJlZmFmMDRjYThiMmZjMjAzNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nOp23-Hwuw95uPqIL91LD_o5xx6ITZL4BBf7BT_kycI)
> 
> Well... I've saw the camera variables on the player script, and i've tried to change some numbers there to make it do something like a "zoom", but it didn't work properly... So if you guys can tell me how i can even start "fixing" that camera, i would finish those tweaks today or tomorrow

I once got a similar problem with the scene being invalid, but you could just copy the scene from a place where it is supposed to work. That's what I did to fix it. Afterwards, I'd advise changing some stuff up depending on what version of the title screen you chose.

**Comment by SrDarkOfc** [comment] 2024-01-30 02:08
> > Hey, one question though. I already made some changes to the viewport, and in the presentations. Unfortunately i couldn't change the title bcs "the scene is invalid/corrupted."
> > But nevermind, i just wanna know now how do i even start to tweak the camera script for the player :v
> > ![Screenshot_2024-01-29-13-37-08-073_org godotengine editor v4](https://private-user-images.githubusercontent.com/151418455/300554424-79578243-8dd4-4337-baff-b19aeb02b8e3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODAyMjIsIm5iZiI6MTcwNjU3OTkyMiwicGF0aCI6Ii8xNTE0MTg0NTUvMzAwNTU0NDI0LTc5NTc4MjQzLThkZDQtNDMzNy1iYWZmLWIxOWFlYjAyYjhlMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMTU4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmJiOGVhNTUxYTg3NDIxYTliMzg1NjJjYzU2YTk0ZWNjYzQ2NjZlNjI3YWJlZmFmMDRjYThiMmZjMjAzNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nOp23-Hwuw95uPqIL91LD_o5xx6ITZL4BBf7BT_kycI)
> > Well... I've saw the camera variables on the player script, and i've tried to change some numbers there to make it do something like a "zoom", but it didn't work properly... So if you guys can tell me how i can even start "fixing" that camera, i would finish those tweaks today or tomorrow
> 
> I once got a similar problem with the scene being invalid, but you could just copy the scene from a place where it is supposed to work. That's what I did to fix it. Afterwards, I'd advise changing some stuff up depending on what version of the title screen you chose.

Sort of i am trying to edit the original "title.tscn" that comes within the latest version of the engine... But i'm not charging for fixing this now, i just wanna fix the player camera :v

**Comment by 2Schoolhouse** [comment] 2024-01-30 02:15
> Sort of i am trying to edit the original "title.tscn" that comes within the latest version of the engine... But i'm not charging for fixing this now, i just wanna fix the player camera :v

Unfortunately the only answer I know to how to fix the title error is by replacing it with one from an older Godot 4 version of said scene. Godot seems to dislike the newer version specifically, and while it can run it from what I remember, it can't seem to edit it.

**Comment by Caverns4** [comment] 2024-09-20 21:37
Mobile support is not something we aim to explicitly support, therefore doesn't belong in "issues". If you want advice/tips on implementing this yourself, that is a topic best suited for "discussions".
To keep the repository tidy, I'll be closing this now.

**Closed by Caverns4** 2024-09-20 21:37 UTC
